apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-php-configmap
data:
  HOST_DB: svc-db-crud-php
  USER_DB: root
  PASS_DB: q1w2e3r4
  DATABASE_DB: crud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-php-deployment
spec:
  template:
    metadata:
      name: crud-php
      labels:
        app: crud-php
    spec:
      containers:
        - name: crud-php-container
          image: luisavelino/crud:1.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: crud-php-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: crud-php
---
apiVersion: v1
kind: Service
metadata:
  name: svc-crud-php
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: crud-php