apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-php-dp
spec:
  replicas: 3
  template:
    metadata:
      name: crud-php
      labels:
        app: crud-php
    spec:
      containers:
        - name: crud-php-container
          image: luisavelino/crud_php-source_code:182e828
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: crud-php-secret
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 300m
              memory: 300Mi
  selector:
    matchLabels:
      app: crud-php