apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-crud-php-dp
spec:
  replicas: 1
  template:
    metadata:
      name: db-crud-php
      labels:
        app: db-crud-php
    spec:
      serviceAccount: db-crud-php-sa
      containers:
        - name: db-crud-php-container
          image: luisavelino/db-crud_php-source_code:5e2b81c
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: db-crud-php-secret
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-storage-pvc
  selector:
    matchLabels:
      app: db-crud-php