apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-crud-php-dp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db-crud-php
      name: db-crud-php
    spec:
      containers:
        - name: db-crud-php-container
          image: luisavelino/mysql-crud_php:1.0
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-crud-php-cfg
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: db-crud-php-pvc
  selector:
    matchLabels:
      app: db-crud-php
  serviceName: db-crud-php-svc