version: '3'

services:
  php:
    build: .
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=challenge

volumes:
  mysql-storage:
